### ISSUE TITLE
Stats vs repoquery

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#116]
Looking at pkgdb stats [1], there is stated that there is 16079 packages currently in Rawhide. However, repoquery gives me different number:

$ sudo dnf repoquery --disablerepo=* --enablerepo=rawhide-source --arch src '*' | wc -l
15994

Is that difference caused by initialized repositories, where package was not reported yet? If this assumption is true, may be it would be worth of listing such repositories somewhere, probably similarly to pending acls [2].

BTW In this light, the term "packages" is probably not the best one when you are counting repositories actually.

[1] https://admin.fedoraproject.org/pkgdb/stats/
[2] https://admin.fedoraproject.org/pkgdb/acl/pending/

**Comment by pypingou** [comment]
Amusing:
``
$ repoquery --disablerepo=* --enablerepo=rawhide-source --arch src '*' |wc -l
16226
``
Which is already much closer to what's in pkgdb

I wonder if there isn't already some behavioral changes between dnf repoquery and the old repoquery

**Comment by pypingou** [comment]
Ok so I investigated this a little more and I think I have the answer.
How to reproduce:

1) Get the packages in rawhide listed in rawhide by repoquery:
``repoquery --disablerepo=* --enablerepo=rawhide-source --arch src '*' > rawhide_pkgs``
2) Get the packages in rawhide listed by pkgdb:
````
import pkgdb2client

pkgdb = pkgdb2client.PkgDB()
pkgs = pkgdb.get_packages(branches='master', status='Approved', page='all')

print len(pkgs['packages'])
with open('pkgdb_rawhide', 'w') as stream:
    for pkg in pkgs['packages']:
        stream.write(pkg['name'] + '\n')
````
3) Compare the two lists:
````
with open('pkgdb_rawhide', 'r') as stream:
    pkgdb_pkgs = set([pkg.strip() for pkg in stream.readlines()])

with open('rawhide_pkgs', 'r') as stream:
    repoquery_pkgs = set([pkg.rsplit('-', 2)[0] for pkg in stream.readlines()])

print len(pkgdb_pkgs), len(repoquery_pkgs)


print 'pkgs listed by pkgdb but not repoquery'
print sorted(pkgdb_pkgs.difference(repoquery_pkgs))

print '\npkgs listed by repoquery but not pkgdb'
print sorted(repoquery_pkgs.difference(pkgdb_pkgs))
````
Examples of packages not in repoquery:
* alot: http://koji.fedoraproject.org/koji/packageinfo?packageID=18978 apparently never built properly in rawhide
* aboot: http://koji.fedoraproject.org/koji/packageinfo?packageID=5067 never built
* mediawiki116-ParserFunctions: http://koji.fedoraproject.org/koji/packageinfo?packageID=11575 never built
* todocli: http://koji.fedoraproject.org/koji/packageinfo?packageID=19771 never built

...

Examples of packages not present in pkgdb:
* cone: Orphaned in rawhide https://admin.fedoraproject.org/pkgdb/package/cone/
* umlgraph: Orphaned in rawhide https://admin.fedoraproject.org/pkgdb/package/umlgraph/
* maven-anno-plugin: Orphaned in rawhide https://admin.fedoraproject.org/pkgdb/package/maven-anno-plugin/

...

So looking at this, it seems that the difference between repoquery and pkgdb stats make sense.

**Comment by voxik** [comment]
Thank you for confirming my initial assumption ... although I am surprised to hear that there are also packages missing from pkgdb.

**Comment by pypingou** [comment]
It's not missing per say, but I asked pkgdb to return only 'Approved' packages (ie: no orphaned or  retired packages)

**Comment by voxik** [comment]
Ah, ok, that makes sense ... should read better :)

**Comment by pypingou** [comment]
Should we close this now?

**Comment by voxik** [comment]
Probably ...
