### ISSUE TITLE
[RFE] Display the reason for retiring package

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#119]
The information that package was retired is not that much visible in PkgDb, but the information why it was actually retired is completely missing, on have to take a look into dist git. This is not very user friendly and should be improved.

**Comment by pypingou** [comment]
Well, pkgdb does not know why a package was retired

**Comment by apevec** [comment]
Retirement reason is stored in dist-git dead.package file, as created by fedpkg retire DESCRIPTION
https://fedoraproject.org/wiki/How_to_remove_a_package_at_end_of_life#GIT

e.g. pkgs.fedoraproject.org/cgit/openstack-nova.git/diff/dead.package?h=el6

**Comment by apevec** [comment]
clickable e.g.
http://pkgs.fedoraproject.org/cgit/openstack-nova.git/diff/dead.package?h=el6

**Comment by pypingou** [comment]
Which just proves what I was saying :smiley:

That being said, I'll see if I can come up with something to somehow integrate the information

**Comment by voxik** [comment]
Thanks for this. However, I am missing the "we underline it" part at least, hence it is not discoverable. I'd prefer if this is shown somewhere in bold, that the package is retired. Also, the committers are still listed as committers, although I'd say they cannot commit anymore to retired branches.

**Comment by pypingou** [comment]
> I am missing the "we underline it" part at least, hence it is not discoverable

Basically, only 'Retired' status are underlined: https://admin.fedoraproject.org/pkgdb/package/Ajaxterm/

I am not sure I like the idea of making it bold and I don't know how I feel about adding colors.
Until now I have not heard of people having problems finding out if a package is active, orphaned or retired.

**Comment by voxik** [comment]
> Basically, only 'Retired' status are underlined:

Ha, the underlining was probably caching issue. Pressing Ctrl+F5 fixed this for me ...

> Until now I have not heard of people having problems finding out if a package is active, orphaned or retired.

I have to disagree. I filled this ticket not because I am missing the information, but because I see others are missing the information and it is not communicated properly. This mailing discussion was the original trigger for this ticket:

https://lists.fedoraproject.org/pipermail/devel/2015-January/206153.html

**Comment by pypingou** [comment]
> Ha, the underlining was probably caching issue. Pressing Ctrl+F5 fixed this for me ... 

Cool :)

> I filled this ticket not because I am missing the information, but because I see others are missing the information and it is not communicated properly

I agree that the information 'why' the package was retired is buried in dist-git, but not the information 'if' the package is retired, that's what I was trying to convey here.
