### ISSUE TITLE
Copy status change timestamps for pkgs when branching (at least for orphaned packages)

### ISSUE THREAD

**Issue by tyll** [fedora-infra/pkgdb2#142]
When F22 was branched, all status_change timestamps for orphaned packages were set to the branching date. This makes it hard to identify packages that are orphaned for more than six weeks and therefore need to be retired. In general since the pkgs are "copied" from Rawhide, it might be a good idea to also copy the status_change timestamp for packages when branching so it is more useful for pkgs in branched.

**Comment by pypingou** [comment]
The timeline should provide this information anyway, but I'll look into it

**Comment by tyll** [comment]
Using the timeline might be a workaround for F22, but is it available via the API? I need the information for the orphaned packages reports:
https://lists.fedoraproject.org/pipermail/devel/2015-February/207636.html

**Comment by pypingou** [comment]
It's not available via pkgdb's API but it'd be on datagrepper as for each action logged to the DB there is a fedmsg message sent

**Comment by pypingou** [comment]
@tyll what do we want to do for this? Is datagrepper enough or do we still want to adjust pkgdb?

In a way, I think that keeping the change timestamp to be the date of the branching make sense since the package was the changed (in this case even created) for the last time at branching.
Maybe you can use the combination of change and create timestamps to figure out if the package was created orphaned or not (and if so, then we can check Fn-1), but ok that does mean 2 calls instead of 1 for some packages.

**Comment by pypingou** [comment]
@tyll thoughts?

**Comment by tyll** [comment]
I did not yet look into using datagrepper for this and just checking the pkgs manually for now. Is there an easy query to get the retirement for a pkg btw or do I have to get all events for a pkg and then search for the retirement event?

**Comment by ralphbean** [comment]
I think the best we have topic-wise is this [status change topic](http://fedora-fedmsg.readthedocs.org/en/latest/topics.html#pkgdb-package-unretire-request) which seem to be mostly [retirement messages in practice](https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.pkgdb.package.update.status).

**Comment by pypingou** [comment]
Ok, with the work of https://github.com/fedora-infra/pkgdb2/pull/331 keeping the status_change would be easy, is this still something we're interested in?

**Comment by tyll** [comment]
I did not get to use fedmsg, therefore this would still be helpful for me.
