### ISSUE TITLE
Alembic scripts for admin_actions stuff?

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#150]
I can't get the latest db dump to work on the master branch because I don't have the admin_actions tables.  I don't see any alembic upgrade scripts for them either.  Are they missing?

**Comment by pypingou** [comment]
You can just re-run the createdb.py script it will create the missing tables :)

**Comment by ralphbean** [comment]
Should I create them?

**Comment by pypingou** [comment]
I don't think it is necessary (I normally use alembic only for operation on existing tables) but I would merge a pull-request if one is submitted :-)

**Comment by ralphbean** [comment]
Nah, if you don't need them for the prod db, then ok.
