### ISSUE TITLE
Show anitya status in the package view interface

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#152]
With buttons!

It could be neat to add some anitya information in the pkgdb interface
specifically, under the Monitoring toggle button, we could have a little widget
that displays.

1) if the package is mapped in anitya
2) if it's not mapped, a list of projects in anitya that share the same homepage with buttons to go and map them
3) if no projects share the same homepage, a button to go add it to anitya

Maybe more a pop-up, otherwise the menu on the right side will become somewhat large.

Make it configurable, with PKGDB2_ANITYA_DISTRO='Fedora' PKGDB2_ANITYA_URL='https://release-monitoring.org'

**Comment by pypingou** [comment]
Implemented in https://github.com/fedora-infra/pkgdb2/tree/monitoring

I'd like to fix https://github.com/fedora-infra/pkgdb2/issues/163 in the same pull-request but I still haven't find a wording I'm happy with.
Do you have any thoughts about this?

**Comment by ralphbean** [comment]
> Do you have any thoughts about this?

I am at a loss.  Let's ask around but wait until we have some wording we agree is good.

**Comment by pypingou** [comment]
Fixed in https://github.com/fedora-infra/pkgdb2/pull/168
