### ISSUE TITLE
Monitoring on/off buttons are confusing

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#153]
I might be the only one, but I really do not understand when the monitoring is on and when it is off. If the button is clickable (i.e. blue), does it mean that after I click it, this will be the next state? Or is the value in blue button the current state? (not mentioning that the white On with shadow looks like key, just to add more confusion ;)

**Comment by voxik** [comment]
Ah, now I noticed the flash message after toggling the state, so at least something ... and it isn't on/off button but toggle :)

**Comment by pypingou** [comment]
The monitoring is on/off, the button is toggle :)

**Comment by pypingou** [comment]
I think this is fixed in https://github.com/fedora-infra/pkgdb2/pull/157
