### ISSUE TITLE
The `Monitoring' flag is misleading

### ISSUE THREAD

**Issue by contyk** [fedora-infra/pkgdb2#163]
The package is monitored no matter what this flag is set to; the only thing it controls, as far as I understand it [0], is whether bugs will be filed or not.

Perhaps it could be renamed to something more descriptive, e.g. `file bug reports: yes/no' or somesuch?

[0] https://fedoraproject.org/wiki/Upstream_release_monitoring#The-New-Hotness

**Comment by pypingou** [comment]
Note that the title (mouse over) is a little more informative when logged in
