### ISSUE TITLE
Retiring a package should turn off the monitoring flag

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#177]
For instance, the cacti package is [retired in rawhide](https://admin.fedoraproject.org/pkgdb/package/cacti/) but the-new-hotness just [filed](https://apps.fedoraproject.org/datagrepper/id?id=2015-3011b32f-77da-4fc9-94c3-7f83fbf51fbf&is_raw=true&size=extra-large) a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1209663) on it (and failed to kick off a scratch build because the repo had only a ``dead.package`` file).

**Comment by pypingou** [comment]
This relates a little bit to https://github.com/fedora-infra/pkgdb2/issues/59 in the way that it requires checking if the package is retired on all branches or not.

I am thinking of making an API endpoint listing the packages retired on all active branches of Fedora/EPEL. From there we could regularly update the monitoring flag and bugzilla.

**Comment by pypingou** [comment]
Once #180 is done this will be easy to do
