### ISSUE TITLE
toggling monitor flag doesn't seem to do anything

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#181]
I'm logged in and I press the monitor-toggle button on this package:  https://admin.fedoraproject.org/pkgdb/package/python-freezegun/  The little UI element slides over but I noticed that no ajax request seems to be going out.  When I reload the page the button reverts to its previous state indicating that nothing has actually changed on the server-side.

**Comment by pypingou** [comment]
hm I can reproduce this in prod, I'll look into it
