### ISSUE TITLE
incompatible with ipsilon (stg)

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#186]
I get a 500 error from ipsilon in stg when I try to log in to pkgdb in stg (but only pkgdb..  none of our other apps do this afaik).  This may just be a problem in ipsilon, but I thought I'd file the bug here so pkgdb devs were aware of it.

**Comment by puiterwijk** [comment]
This is a bug in Ipsilon that sneaked in during internal redesigns. Will fix this upstream.
