### ISSUE TITLE
Add a new flag just for hotness scratch builds

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#187]
In addition to the ``monitor`` flag, it might be nice to be able to specify that "yes I want bugs filed, but I don't want auto scratch builds.

For this we would just need 1) a new column in the db for the new flag and 2) a way to toggle it.

This relates to #163 in that it will either clarify or muddle the meaning of the buttons in the UI as more are added (depending on how its done).

**Comment by pypingou** [comment]
Any idea UI wise?

I thought of two ways:
* a three state button (Do not Monitor/Monitor/Monitor but no scratch build)
* a second toggle button that only appears when the first one (monitoring) is set to True

**Comment by pypingou** [comment]
Or a drop-down list

Note: we could avoid adding a column to the DB by just using 3 states on the current field: Yes/No/Yes_nobuilds (or so)

**Comment by ralphbean** [comment]
A three states button could be cool.. but it depends on how its executed as to whether or not it makes things more or less confusing to the user.

A drop-down list is less pretty than the fancy sliding button.. but it is probably the most clear.
