### ISSUE TITLE
The new package request is confusing

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#190]
![snimek z 2015-05-13 12 40 35](https://cloud.githubusercontent.com/assets/14406/7608817/7234e74c-f96d-11e4-9be5-3af6ce9553d3.png)

For new package, I want to have my request processed as fast as possible, why it mentions some 7 days period etc? Although it says it should be in Awaitng Review state, I can't set such state (although since the request was already processed, it probably was in that state?!?)

**Comment by voxik** [comment]
Also note that the sentence "During these 7 days" is totally without context, which should be nice to provide.

**Comment by pypingou** [comment]
Ok with the changes above merged, let's see if the next release (will be after freeze is over) is better :)

Thanks for your inputs!
