### ISSUE TITLE
[RFE] New package request does not allow to specify comaintainers

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#192]
Not sure if this is really worth of implementation, since maintainers can be added later. It is just difference from previous procedure, so I am asking if you considered this (not really issue for myself ;))

**Comment by pypingou** [comment]
I thought about it and then thought it was easy enough to add co-maintainers after :)

**Comment by voxik** [comment]
Ok, so may be we can close it. I have not checked documentation though. Is this mentioned somewhere?

**Comment by pypingou** [comment]
Not sure about that :)

**Comment by pypingou** [comment]
I'm going to mark this as an easyfix as all what is needed is to add a file to the documentation with some sort of ``frequently asked question`` page

**Comment by puntogil** [comment]
if possible, how can set InitialCC with java-sig in  pkgdb for  a new package?
thanks

**Comment by pypingou** [comment]
As mentioned above, you can't set a CC when making a request, but it's quite simple to add people or group afterward :)

**Comment by puntogil** [comment]
with an "Package Change Request" template? i tried some time ago but dont work ...
do not accept java-sig ...
i prefer always add this for all my packages
any suggestion?
thanks

**Comment by pypingou** [comment]
Once the package is created you can add other packagers, pseudo-users or groups:

1. Go to one of your package: https://admin.fedoraproject.org/pkgdb/package/apache-commons-chain/
2. Click on: Manage the <committers/watchers/admins> any of these
3. There is then an ``Add someone`` button you can use

**Comment by pypingou** [comment]
Oupsy, this isn't closed yet

**Comment by puntogil** [comment]
it seems that something wrong  "User "java-sig" is not in the packager group"

**Comment by pypingou** [comment]
Ok so that's a missing feature as ``java-sig`` is a pseudo-user which means a) not a real account, b) hasn't signed the fpca nor a member of the packager group.

I've just find a way to go around this situation, hopefully that'll be fixed by later tonight or tomorrow.
Sorry for the inconvenience

**Comment by puntogil** [comment]
thanks
see https://admin.fedoraproject.org/pkgdb/packager/java-sig/
https://fedoraproject.org/wiki/PackageDB_admin_requests#Pseudo-users_and_Groups_for_SIGs
seem reported an wrong email
should be
java-sig-commits[AT]lists.fedoraproject.org
instead of
java-devel[AT]lists.fedoraproject.org
or this is an my only mistake

**Comment by pypingou** [comment]
I edited the wiki, thanks for the pointer :)

**Comment by pypingou** [comment]
Fixed in https://github.com/fedora-infra/pkgdb2/pull/253
