### ISSUE TITLE
I cannot logout from page which requests my credentials.

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#193]
I wanted to log out from package request page [1], when when I press logout, I am immediately logged in again. This is a bit unexpected behavior. There should be redirect to some RO page I am proposing in #191

[1] https://admin.fedoraproject.org/pkgdb/package/requests/119

**Comment by voxik** [comment]
But I suspect this issue might demonstrate itself also on other pages, although I did not tried it.

**Comment by pypingou** [comment]
It will be the case on all pages requiring authentication
