### ISSUE TITLE
[RFE] Provide link for simple addition of package to Anitya

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#194]
Currently, the Anitya pop-up provides just link to https://release-monitoring.org/ but it could do better, e.g. provide link for simple creation of the package in monitoring, or provide list of something which could represent my package in Anitya. In my case, for vim-fugitive, it coud provide list of monitored packages which already contains words such as vim or fugitive.

**Comment by pypingou** [comment]
I guess we could add a link to create the project on anitya if we fail to find the project there.

The risk however is that the user adds a duplicate project while what is missing isn't the project but the mapping.

**Comment by voxik** [comment]
> The risk however is that the user adds a duplicate project while what is missing isn't the project but the mapping.

Agree, that is why I proposed to provide some list of potential matches to limit the issue. Also, checking upstream URL for duplicates would help to mitigate this issue
