### ISSUE TITLE
Make the package name link to package page in the requests page

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#201]
It would be nice if the package name (e.g. vim-fugitive) on the requests page[1], would become link to the actual package page [2] when the package exists.

[1] https://admin.fedoraproject.org/pkgdb/packager/vondruch/requests
[2] https://admin.fedoraproject.org/pkgdb/package/vim-fugitive/

**Comment by pypingou** [comment]
We can't link for package.request, we can for branch.request and we do not know at what point the package.request transforms into a branch.request, so this is unfortunately a cantfix.

**Comment by voxik** [comment]
Once the request is processed, then you can link .... or I can't see why you should not be able to do that.

**Comment by pypingou** [comment]
Using the status then, maybe yes, but that won't work for all pending/denied/awaiting review requests.

**Comment by voxik** [comment]
Definitely, as I already said in my initial comment:

> when the package exists.

**Comment by pypingou** [comment]
Ok so this is a matter of checking the status of the request in the template and adding the link when possible, making this an easyfix :)

**Comment by trishnaguha** [comment]
@pypingou I would like to work on it. Can you provide me link to start with?
Thank you :)

**Comment by pypingou** [comment]
@trishnaguha Cool! The first step will be to get you an instance of pkgdb2 running locally :)

**Comment by TridevGuha** [comment]
What is the next step after running pkgdb2 locally?

**Comment by pypingou** [comment]
Then you'll need to make yourself an admin either by changing the default configuration and putting in a group that you're in or by changing the method that check if you're an admin and make it return True.

Then you can create requests for new packages and approve them.

Then you should have what's needed to fix this ticket :)

**Comment by TridevGuha** [comment]
I have found an issue at the time of setting up pkgdb2 in virtualenv following this link: 
https://github.com/fedora-infra/pkgdb2 
The problecm when exectuting command 'pip install -r test_requirements.txt' to run tests before running the server comes up with the error in this link: https://paste.fedoraproject.org/271918/39224144/ 
 how can i set up 'pip install -r test_requirements.txt' without error?
Thanks :)

**Comment by trishnaguha** [comment]
@TridevGuha  install postgresql-devel

**Comment by pypingou** [comment]
Any progress on this one?

**Comment by TridevGuha** [comment]
https://paste.fedoraproject.org/279669/14449332/
this error is coming up when running the server.

**Comment by pypingou** [comment]
@TridevGuha still stuck on this? need help with something? :)

**Comment by TridevGuha** [comment]
Now the server running, thanks :)

**Comment by TridevGuha** [comment]
how to point sqlachemy.url to postgresql?
in this line in alembic.ini:    sqlalchemy.url = driver://user:pass@localhost/dbname

**Comment by TridevGuha** [comment]
having problem to point sqlalchemy.url to postgresql in the line 
sqlalchemy.url = driver://user:pass@localhost/dbname

**Comment by pypingou** [comment]
``sqlalchemy.url`` is in the alembic file, you shouldn't need this.

What you want to change is the ``default_config.py`` file and the string should look like:
``DB_URL = 'postgresql://user:password@localhost/dbname``
Where you replace ``user``, ``password`` and ``dbname`` by the username and password used to connect to postgresql and the name of the database in the postgresql server.

**Comment by TridevGuha** [comment]
ok

**Comment by pypingou** [comment]
Any new for this? Need help with something?
