### ISSUE TITLE
Package description does not preserve original formating

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#202]
The package description in pkgdb [1] does not contain any formating, as is available in the .spec file. Not sure where it get lost. Might it be issue in pkgdb_updater?

[1] https://admin.fedoraproject.org/pkgdb/package/vim-fugitive/
[2] http://pkgs.fedoraproject.org/cgit/vim-fugitive.git/tree/vim-fugitive.spec

**Comment by pypingou** [comment]
This can be fixed/improved by adding ``white-space: pre;`` to the correct css identifier, making this an easyfix

**Comment by farhaanbukhsh** [comment]
@pypingou I want take a stab at this. I cloned it and made it run but one thing do i need a fedora machine to request package and all.

**Comment by pypingou** [comment]
pkgdb2 itself is a web-app so you should be able to run it on all/most systems :)

**Comment by farhaanbukhsh** [comment]
![selection_033](https://cloud.githubusercontent.com/assets/7670449/10106050/0191249c-63d0-11e5-9f90-8764946192ff.png)

How does it look?

**Comment by pypingou** [comment]
Waaaayyyy too big, but that's not pkgdb's problem so it looks good :)

**Comment by farhaanbukhsh** [comment]
That's the worst case , edge case i guess so should I send a PR?

**Comment by pypingou** [comment]
Fixed by https://github.com/fedora-infra/pkgdb2/pull/226
