### ISSUE TITLE
Explain more about the monitoring buttons

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#204]
It's not 100% clear what they do.  When you click 'bugs and builds' are you going to get bugs and builds about the package or are you going to get emails about bugs and builds?  (it's the first one)

We could add some tooltips to the buttons to explain more fully what they do, maybe?

**Comment by Devyani-Divs** [comment]
Hi @ralphbean @pypingou , :) i wish to work on this bug. Can you provide me with a few links to begin with. Thankyou.

**Comment by pypingou** [comment]
It would be about adding a ``title`` to this section of the code:
https://github.com/fedora-infra/pkgdb2/blob/master/pkgdb2/templates/package.html#L38-L51

**Comment by farhaanbukhsh** [comment]
@ralphbean @pypingou If nobody is working on this issue I would like to take this up.

**Comment by Devyani-Divs** [comment]
Hello @farhaanbukhsh , was caught up with my intern work. I will work on the bug.
@ralphbean @pypingou ,apologies for taking so long.

**Comment by farhaanbukhsh** [comment]
@Devyani-Divs  cool :+1:

**Comment by pypingou** [comment]
I think this has been fixed by:
https://github.com/fedora-infra/pkgdb2/pull/250
and
https://github.com/fedora-infra/pkgdb2/pull/247
