### ISSUE TITLE
Nonintuitive behavior of monitoring buttons

### ISSUE THREAD

**Issue by msimacek** [fedora-infra/pkgdb2#208]
The monitoring buttons are in fact radio-buttons, but since they are rendered as normal buttons, it's quite non-obvious that they work in that way. I just had to ask a colleague how to turn upstream release monitoring on, because I honestly couldn't figure it out and kept clicking on "No monitoring", expecting it to toggle. I think they should use regular radio button widget or have better graphics that convey the radio-button nature clearly. The current arrow on selected button is not enough.

**Comment by jasontibbitts** [comment]
Honestly I'd suggest a dropdown instead of the radio buttons.

**Comment by Devyani-Divs** [comment]
@pypingou worked on tooltip for monitoring button #204 .
Can I work on this ? Let me know, if we wish to make it a radio button or a dropdown.
Thanks :)

**Comment by pypingou** [comment]
I think this got fixed by the PR above. Thanks for the report and the fix :)
