### ISSUE TITLE
Don't request ACLs on retired branches by default

### ISSUE THREAD

**Issue by msimacek** [fedora-infra/pkgdb2#209]
"Request commit access" button requests commit access on all branches. The same for "Request admin access". I think it would be more logical if it would request acls only on branches that aren't retired (user can still manage the acls per-branch if he wants to). Reasoning: There are lot of packages that have EPEL branches retired and when I want to become a comaintainer of the package, I usually don't want to unretire those.

**Comment by trishnaguha** [comment]
I would like to work on it

**Comment by pypingou** [comment]
@trishnaguha any progress on this? Need help with it?

**Comment by trishnaguha** [comment]
@pypingou Sorry I was afk for last 5-6 days, couldn't work on the issue. I need help to make myself packager for testing purpose.

**Comment by trishnaguha** [comment]
@pypingou Let me know whether I am on right track to make myself admin or not. "Request Admin access" on this package "0ad" has turned in to "Give up Admin Access". But "Request Commit Access" still shows "You must be a packager". 
![screenshot from 2015-10-24 12-42-22](https://cloud.githubusercontent.com/assets/13337039/10709460/43c20fe6-7a4d-11e5-85d6-df03c8e7fb91.png)

**Comment by pypingou** [comment]
You can maybe hack https://github.com/fedora-infra/pkgdb2/blob/master/pkgdb2/ui/__init__.py#L78 to add the 'packager' group to your list of groups

**Comment by trishnaguha** [comment]
@pypingou But I made the changes here https://github.com/fedora-infra/pkgdb2/blob/master/pkgdb2/lib/__init__.py#L58

**Comment by pypingou** [comment]
Then you will have to adjust https://github.com/fedora-infra/pkgdb2/blob/master/pkgdb2/__init__.py#L179 as well

**Comment by pypingou** [comment]
Ok so this ticket is available for anyone to work on
