### ISSUE TITLE
/usr/bin/update_package_info.py needs updating for current releases

### ISSUE THREAD

**Issue by nirik** [fedora-infra/pkgdb2#211]
/usr/bin/update_package_info.py currently has f20 in it, and not f23. 

Perhaps it could either: 

a) pull the current release info from the api/db.

b) at least split it out into the cfg file for easier changes. 

If not, then we need to manually adjust this and make a new release with the updated release info each time we change them. :(

**Comment by nirik** [comment]
BTW, this currently results in our cron tracebacking: 

f20_up: fedora/linux/updates/20
Traceback (most recent call last):
  File "/usr/bin/update_package_info.py", line 235, in <module>
    main()
  File "/usr/bin/update_package_info.py", line 145, in main
    db_ext = primary_db_location.split('primary.')[1]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by pypingou** [comment]
I went with the solution b) since we need the mapping (and repos may change)

**Comment by pypingou** [comment]
This is now the case, we should just put the right config into ansible so that we don't forget to update it next time :)
