### ISSUE TITLE
Package search: exact match or substring?

### ISSUE THREAD

**Issue by frafra** [fedora-infra/pkgdb2#213]
If I look for "xyz" on https://admin.fedoraproject.org/pkgdb/ it will look for "xyz\*". I think that it would be better to look for "xyz" (exact match and let the user decide where to use wildcards) or "\*xyz\*" (substring).

**Comment by pypingou** [comment]
If you search for ``xyz`` it will replace it by ``xyz*`` but if you adjust the URL:
https://admin.fedoraproject.org/pkgdb/packages/xyz/
Then it won't add back the ``*``

**Comment by frafra** [comment]
Yes, I saw how the url changes. I was just thinking that maybe a substring search (or an exact match) would be better than looking for packages "starting with" a string. But this is really a minor thing, a little suggestion/idea, nothing more :)

**Comment by Devyani-Divs** [comment]
@pypingou does this bug needs to be fixed? If yes, would like to fix it ! :)

**Comment by pypingou** [comment]
I'm not quite sure I want to change the behavior, anyone minds if I close the ticket?

If more people disagree with this, I would be willing to reconsider.

**Comment by pypingou** [comment]
Closing then :)
