### ISSUE TITLE
Koschei switch-input disabled for non-commiters

### ISSUE THREAD

**Issue by mizdebsk** [fedora-infra/pkgdb2#215]
Koschei monitoring switch-input is disabled for non-commiters and non-admins. All packagers are allowed to toggle monitoring (and it works, tested with API and packagedb-cli), so monitoring switch should be enabled to non-owners too.

```
                <input type="checkbox" class="switch-input" name="koschei" id="koschei"
                  {%if package.koschei %}checked="checked"{% endif %}
                  {% if not(g.fas_user.username in admins
                            or g.fas_user.username in commiters
                            or is_admin) %} disabled="disabled"{% endif %} />
```

**Comment by pypingou** [comment]
You mean the action is blocked in the UI while it's allowed via the API?

**Comment by mizdebsk** [comment]
> You mean the action is blocked in the UI while it's allowed via the API?

Yes, exactly.

**Comment by pypingou** [comment]
Ok def a bug, thanks for the report and the pointer.

Marking it easyfix and I'll get to it if no-one fix it before me
