### ISSUE TITLE
Toggling Koschei flag through Web UI not working for packages without ACL

### ISSUE THREAD

**Issue by mizdebsk** [fedora-infra/pkgdb2#218]
In pkgdb2 currently deployed in staging, toggling Koschei boolean in Web UI is not working for packages on which I don't have ACLs.

Reproducer:
- log in through Web UI as user who is packager, but not pkgdb2 admin
- go to package you don't have ACLs on, eg.: https://admin.stg.fedoraproject.org/pkgdb/package/bash/
- toggle Koschei switch to opposite state

Expected result:
- the package is added to or removed from list at https://admin.stg.fedoraproject.org/pkgdb/api/koschei
- fedmsg is emitted

Actual result:
- package state is not changed
- fedmsg is not emitted
- after reloading pkgdb2 web page, Koschei boolean is in the original state

**Comment by mizdebsk** [comment]
Also note that toggling Koschei flag works with API, using packagedb-cli.

**Comment by pypingou** [comment]
Found it, it's an issue in the template.
