### ISSUE TITLE
Clarify status of using pkgdb for package requests

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#219]
https://fedorahosted.org/rel-eng/ticket/5931

The wiki mentions it as "coming in the future".  Is it just not official yet?  Is it still optional?

/cc @mathstuf

**Comment by pypingou** [comment]
It's currently still optional, it's up to rel-eng to flip the switch and make it the only way if they want to.

**Comment by mathstuf** [comment]
I don't see any (obvious) indication that this occurred:

```
we will evaluate in two weeks when to shut down the old method for requesting branches
```

(from the Trac ticket). Did it not get linked to from that ticket?

**Comment by pypingou** [comment]
AFAIK, there was no such evaluation yet indeed, still is a rel-eng issue though :)

**Comment by pypingou** [comment]
UI has improved and we're about to announce the switch apparently :)

**Comment by pypingou** [comment]
This has been cleared up https://lists.fedoraproject.org/pipermail/devel-announce/2015-October/001686.html

Thanks @nirik
