### ISSUE TITLE
New packages shouldn't be allowed to have an empty upstream_url

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#221]
This is a proposal.

Allowing an empty upstream_url field negatively affects the-new-hotness, specifically in fedora-infra/the-new-hotness#46.  It seems reasonable to me to require new pkgdb packages to specify an upstream_url in the beginning.  It seems like we've been moving that way anyways with the current package review process, no?

**Comment by pypingou** [comment]
While I agree, we've heard of the situation where there are no upstream_url, I would have to dig through the emails from the devel list but it was one of the point raised when we changed the format to request new packages.

**Comment by pypingou** [comment]
Found the discussion https://lists.fedoraproject.org/pipermail/devel/2014-May/199214.html

**Comment by ralphbean** [comment]
OK.  Thanks!  :)
