### ISSUE TITLE
change bugzilla url to bug # for request new package

### ISSUE THREAD

**Issue by nirik** [fedora-infra/pkgdb2#229]
Change the form to just have a entry for the bug number instead of the entire  bugzilla url. 

Since it's always going to be https://bugzilla.redhat.com and we don't want people to use it to attack other sites.

**Comment by pypingou** [comment]
They won't be able to attack other site, whatever url they enter we extract the identifier and query bugzilla with it.

That being said, we could definitely ask for only a bug number

**Comment by pypingou** [comment]
The original reason for asking for the link instead of just the bug number was to be independant from bugzilla allowing:
- Other infrastructure to use pkgdb2 w/o bugzilla (or with their own bugzilla)
- Be ready to move reviews off bugzilla (fresque come here my friend!!)
