### ISSUE TITLE
pkgdb-admin improvements

### ISSUE THREAD

**Issue by nirik** [fedora-infra/pkgdb2#231]
Would be nice to have a few improvements to pkgdb-admin: 

1. Right now it seems to ask for password several times: 
```
% pkgdb-admin process 411
#411 (Awaiting Review) - mclasen requested the new package "fedora-workstation-repositories" on "master"
FAS password for user kevin: 
 ! User pfrields@redhat.com is not a packager

What should we do about this requests?
approve, deny, pass: approve
FAS password for user kevin: 
Package created
```

2. It would be nice to show the bugzilla url for the review so the admin could click on it easily and go look at the review before approving.

**Comment by pypingou** [comment]
The first one shouldn't be, odd :/

The second one is doable sure

**Comment by pypingou** [comment]
The first issue about the FAS login, I can't reproduce locally, maybe try to prune your ``~/.cache/pkgdb-session.pickle`` to see?

**Comment by nirik** [comment]
ok, cleaning out my ~/.cache/pkgdb-session.pickle seems to have fixed the first one. ;)
