### ISSUE TITLE
Leave a message for non-admins on clicking monitoring buttons

### ISSUE THREAD

**Issue by Devyani-Divs** [fedora-infra/pkgdb2#246]
![screenshot from 2015-10-12 01 04 32](https://cloud.githubusercontent.com/assets/4932704/10418618/d6b10674-707d-11e5-8dbd-b6c3c3d0c683.png)
some random user is logged in or not, one doesn't get any response on clicking "Bugs and builds". Its really annoying(I spent a couple of hours to come up with a reason, even concluded might be because I have less number of badges :P )
We can either leave a message for the user or as @ralphbean suggested, we can make the buttons non-clickable by not changing the cursor into a pointer-finger in case the user ain't the package admin or the owner of the package.

**Comment by pypingou** [comment]
Changing the mouse pointer +1, we could also add something like you did in #245 when the user is not logged in (like what's on the koschei button)

**Comment by Devyani-Divs** [comment]
#247 fixes it.
