### ISSUE TITLE
When listing requests for new packages and display page 2 I get access denied

### ISSUE THREAD

**Issue by ingvagabund** [fedora-infra/pkgdb2#252]
Hi,

when I am listing all my request for new packages in pkgdb [1] and want to display page 2 (clicking next) I get:
```vim
"You are not an administrator of pkgdb"
```
This should not happen. Links for Next and Previous are incorrect. The current link for page 2 (Next) is:
```vim
https://admin.fedoraproject.org/pkgdb/admin/actions/?from_date=&page=2&package=
```
Correct link is:
```vim
https://admin.fedoraproject.org/pkgdb/packager/jchaloup/requests?page=2
```

[1] https://admin.fedoraproject.org/pkgdb/packager/jchaloup/requests

**Comment by pypingou** [comment]
Thanks for the report, this is indeed a bug
