### ISSUE TITLE
Introduce an allow_retires flag on the collection table

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#257]
We ran into problems with the way #81 was done this week, when @tyll set the status of the F23 branch to 'Active' in order to disallow retires for final freeze.... but in the meantime, other systems have come to depend on that status field to mean other things.  We expected that it wouldn't be set to Active until after F23 GA (which is not for another few weeks).

To get around this, we were talking about adding another flag to the collection table to do what #81 wanted, so that we can then free up the 'status' field to indicate a more general status.

**Comment by tyll** [comment]
another option would be a final_freeze flag to model the current development process and use it to decide whether or not retirement is possible in branch that is in the development state. This could also be used to e.g. block stable pushes in Bodhi or other tasks that depend on it - if others agree.

**Comment by tyll** [comment]
btw. after this is changed, the schedule needs to be adjusted as well:
https://fedorapeople.org/groups/schedule/f-23/f-23-releng-tasks.html

**Comment by pypingou** [comment]
I like the ``allow_retire`` approach more and it is self-explaining from pkgdb's point of view while ``final_freeze`` means that you must know what the final freeze is and what it implies, plus the meaning of ``final_freeze`` changes over time, just see it now, it didn't use to mean we block retirement and now it does.
