### ISSUE TITLE
Problem with the pager links

### ISSUE THREAD

**Issue by jaredsmith** [fedora-infra/pkgdb2#261]
If I click on the "My Requests" tab in pkgdb while logged in, I get the first page of my requests.  At the top of the list are some pager links to go to the next page, etc.

The "Next >" link, however, seems to go to the wrong location.  It links to https://admin.fedoraproject.org/pkgdb/admin/actions/?from_date=&page=2&package= and I think instead it should link to https://admin.fedoraproject.org/pkgdb/packager/jsmith/requests?page=2

I can't figure out why it would be linking /pkgdb/admin/actions, so I'm guessing this was a copy/paste error or some other kind of oversight.

**Comment by pypingou** [comment]
That's indeed a bug, that has been fixed in https://github.com/fedora-infra/pkgdb2/pull/254

To be release after freeze, sorry for the inconvenience :(
