### ISSUE TITLE
[RFE] Request a new package improvment

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/pkgdb2#269]
When using "Sync" (with from bugzilla) button to fill the "Request a new package" form, would be nice to check if

* bug have fedora-review+ flag 
* bug is assigned

This will avoid to create invalid request.

**Comment by pypingou** [comment]
The code to change is in: https://github.com/fedora-infra/pkgdb2/blob/master/pkgdb2/api/extras.py#L699
