### ISSUE TITLE
Unretirement requests should request the similar information as new package requests

### ISSUE THREAD

**Issue by tyll** [fedora-infra/pkgdb2#277]
To unretire branches, request the information that is also asked for new packages:
https://admin.fedoraproject.org/pkgdb/request/package/

- The package name can be prefilled
- The bug number is only required if the master branch needs to be unretired or if it is kept retired but an EPEL branch is unretired

**Comment by pypingou** [comment]
So the information are:
* name
* bug number
* branches

For which the only info missing is the bug number (compare to the current situation), right?

**Comment by pypingou** [comment]
I have worked on adding support to require a review_url, but would like to hear back from you before opening the pull-request :)

**Comment by tyll** [comment]
yes, the bug number is the only important information that is missing. The other information such as summary, description and upstream URL might be worth to be updated as well. But now that I think about it, the latter information will be updated automatically by pkgdb after the package was built, so it might be omitted.

However, the bug number is also only required on certain conditions (I hope I have them right):

- if the master branch is retired for more than two weeks
- unless an EPEL branch should be unretired that is retired less than two weeks, then no re-review is needed for the EPEL branch

**Comment by pypingou** [comment]
ok I can add the check, but I don't think I can for the two weeks period :(
