### ISSUE TITLE
not possible to set "awaiting review" for unretiring packages

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-infra/pkgdb2#286]
![screenshot from 2015-11-29 17-29-07](https://cloud.githubusercontent.com/assets/2866862/11458370/d4660cb8-96be-11e5-8ba2-45b866b3aea7.png)

**Comment by pypingou** [comment]
Ok, I changed the status for you so that it can be processed, but there is a bug in here somewhere :)

**Comment by ignatenkobrain** [comment]
@pypingou can you do the same for https://admin.fedoraproject.org/pkgdb/package/requests/1887 ?
Thanks.

**Comment by pypingou** [comment]
Fedora branch will be automatically approved once the package is un-retired. So we might actually want to close it and re-open one when master will be ready.
