### ISSUE TITLE
Outdated fedorahosted info, link at bottom of the page

### ISSUE THREAD

**Issue by scop** [fedora-infra/pkgdb2#310]
Clicking the pkgdb2 link at the page footer takes one to https://fedorahosted.org/pkgdb2/ . I guess just about all of the info there is outdated and pkgdb2 related source code and issues should be accessed here instead of fedorahosted. Please update the link, and also the info in the fedorahosted page to point here (in case here's desirable -- I can't know, just guessing).

**Comment by pypingou** [comment]
What makes you think fedorahosted is outdated?

**Comment by scop** [comment]
Ah I see code is a clone in both repos.

To answer your question: issue tracker activity: much more here than in fedorahosted. I'm assuming the intent is not to keep using two issue trackers.

**Comment by pypingou** [comment]
I've always supported both location since github isn't FOSS while trac is.

I might just move to pagure at one point and that'll solve the question :)

**Comment by pypingou** [comment]
Let's close this for now :)

**Comment by scop** [comment]
Yeah, adding a third site would really help :)

Seriously, it's quite hard to figure out where the source code and tracker for various Fedora projects lives nowadays.

**Comment by pypingou** [comment]
On Fri, Jan 01, 2016 at 11:41:34AM -0800, Ville Skyttä wrote:
>    Yeah, adding a third site would really help :)

^_^

>    Seriously, it's quite hard to figure out where the source code and tracker
>    for various Fedora projects lives nowadays.

Most projects link to it in a place or another. Project like pkgdb or fedocal
live in two places which has pros and cons.

I'd say in doubt take the first one you see and if it's not the proper location
someone will tell you :)

**Comment by scop** [comment]
> I'd say in doubt take the first one you see and if it's not the proper location someone will tell you :)

...or not, if it happened was the wrong place, nobody's looking there any more, the code there was outdated and the stuff I worked on and posted as a pull request for had moved on and the PR no longer applies. I've had it happen to me already for a few times and it's very annoying. It's important to let people know where stuff happens and not make them guess or wait for a reply that will never come.

**Comment by pypingou** [comment]
> It's important to let people know where stuff happens and not make them guess or wait for a reply that will never come.

Agreed of course, but do you think the infra team is doing a bad job at this?

**Comment by scop** [comment]
Not necessarily, it's hard to know what team is taking care of what. One example is fedpkg which has moved to pagure but there's no notice of that at fedorahosted.

**Comment by pypingou** [comment]
fedpkg is a good example, it is also a project with a complicated history regarding its upstream and maintenance, hopefully we'll find it a good home soon.
