### ISSUE TITLE
Show list with admin privileges in user profile

### ISSUE THREAD

**Issue by pvalena** [fedora-infra/pkgdb2#311]
Packages, where i have only admin privileges (no watch or commit ACLs) are not listed on my profile.
![snapshot8](https://cloud.githubusercontent.com/assets/15652483/12088314/4937123a-b2da-11e5-8a4b-15a6e784c28a.png)

**Comment by pypingou** [comment]
I think it assumes that if you are not watching nor committing to the package then you are not maintaining it, even if you have admin rights on it.

Maybe something to reconsider, don't know yet :)

**Comment by yash14123** [comment]
Please assign me this task. 
Thanks.

**Comment by pypingou** [comment]
Note that I am still not sure if I want this to be fixed or not. I think the current semantic is correct and ``approveacls`` isn't ``commit``.

**Comment by pypingou** [comment]
I'm going to close this ticket, the more I think about it the more I think the current semantic is correct.

If people feel strongly about it, maybe I'll reconsider.
