### ISSUE TITLE
RFE: allow quering of more than one package name via the API

### ISSUE THREAD

**Issue by jasontibbitts** [fedora-infra/pkgdb2#317]
I have a need to look up the owners of a number of packages on a particular branch as part of formatting a build failure report.  Currently all I can think of doing is to query https://admin.fedoraproject.org/pkgdb/api/package/{}?branches={} a couple hundred times.  It doesn't take _too_ long, but it would be nice if I could save some round trips.

Trying to fetch the whole thing via https://admin.fedoraproject.org/pkgdb/api/packages/?acls=true times out before providing any data (which is understandable).  The data available from the bugzilla endpoint might work but isn't broken down by branch (just Fedora and EPEL).

It would be super great if api/package/ took multiple packages somehow.  Either via splitting on commas or spaces(since package names can't contain them), taking multiple pkgname= arguments, or, well, anything.  The endpoint already returns an array of packages so it appears to be set up to do this already.

Thanks!

**Comment by pypingou** [comment]
I wonder if it wouldn't make more sense to adjust the ``/api/packages`` endpoint to accept multiple patterns, since semantically ``/api/package`` should only return info about a single package

**Comment by pypingou** [comment]
You can test it in staging if you like :)
