### ISSUE TITLE
namespace is not included in dead.package git urls

### ISSUE THREAD

**Issue by apevec** [fedora-infra/pkgdb2#319]
namespace parameter was added in https://github.com/fedora-infra/pkgdb2/commit/08104fc65744593b08a3d1a48c18c44b3016c9f4
but def api_dead_package(pkg_name, clt_name)[1] doesn't use it and clicking "Retired" links fail with No `dead.package` file found in javascript popup.

[1] https://github.com/fedora-infra/pkgdb2/blob/master/pkgdb2/api/extras.py#L628

**Comment by pypingou** [comment]
Which package were you checking?

Because right now, since there is only one namespace in prod (``rpms``) and cgit should be backward compatible, this should have no impact.

**Comment by apevec** [comment]
e.g. https://admin.fedoraproject.org/pkgdb/package/rpms/openstack-nova/ but also others

Generated javascript has:
var url = "/pkgdb/api/dead/package/openstack-nova/?namespace=rpms";

**Comment by pypingou** [comment]
Looks like you found the bug, the correct url is: https://admin.fedoraproject.org/pkgdb/api/dead/package/openstack-nova/master?namespace=rpms

Is this something you would be interesting in fixing ?

**Comment by apevec** [comment]
So I had a look and it's unholy mix of flask and javascript!
PR coming, tested locally w/ production dump.

**Comment by pypingou** [comment]
> So I had a look and it's unholy mix of flask and javascript!

As in, you think we could improve on this or is this just an judgment call?

**Comment by apevec** [comment]
No, just general bitching, ignore me. I'm not frontend developer and I just don't like javascript.
