### ISSUE TITLE
Create a fedmsg service that keeps certain pkgdb namespaces in sync

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#329]
This is related to #328.

We need some kind of fedmsg-based service (external to pkgdb2) that listens for changes on ACL entries for things in the ``rpms/`` and ``dockerfiles/`` namespaces.  When those get updated, we just want to mirror those ACL changes over to the corresponding ``rpms-checks/`` and ``dockerfiles-checks/`` entries.

**Comment by ralphbean** [comment]
High-level tracking ticket:  https://phab.qadevel.cloud.fedoraproject.org/T752

**Comment by tflink** [comment]
Any guesses on how much time this would take? We're a couple weeks out on our initial implementation of dist-git style checks and while we'll probably do our initial testing with a namespace somewhere else, I'm trying to keep ahead of what will eventually be needed to move into production

**Comment by ralphbean** [comment]
It shouldn't take long to write at all.. deployment should be standard, and a debugging period following that.

**Comment by pypingou** [comment]
We can add ``rpms-checks`` in staging whenever we can

**Comment by tflink** [comment]
It's taking a little longer than we had hoped but at this point, I'm expecting to land the initial bits in our develop branch in the next week or two.

In the mean time, we're testing with a "fake dist-git" https://bitbucket.org/fedoraqa/fake-distgit

**Comment by puiterwijk** [comment]
Just wondering, but why does this need to be external to pkgdb?
Couldn't we just tell it that if it needs to get the ACL set for $whatever-checks, it needs to instead look in $whatever?

**Comment by ralphbean** [comment]
I dunno.. it feels like we start cramming all these process rules in pkgdb, and I expect we'll want to change them frequently when we first launch this.

**Comment by puiterwijk** [comment]
I'm even wondering why pkgdb needs to add this? Couldn't we just teach the scripts that generate the dist-git repos and the gitolite acls about the $namespace-checks?
That sounds like a lot smaller effort to me, and less fragile.

**Comment by ralphbean** [comment]
OK - after discussion in IRC, one of @puiterwijk's ideas here seems to be the winner:

We're going to not even touch pkgdb.  pkgdb will be ignorant of the taskotron namespaces and not even know that they exist.

In our existing scripts that copy the ``rpms/`` namespace acls from pkgdb to disk on ``pkgs02``, we're going to modify those to also copy the ``rpms/$PACKAGE`` acls into place for ``rpms-checks/$PACKAGE``.

This way, we don't have to have a special sync service, prone to breakage.  And we don't have to code anything special into pkgdb itself.

We need a big fat comment in the sync script to explain this though, and it should link to this issue for the history.

**Comment by ralphbean** [comment]
Trying this out here:

- https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=978de21bab2729d31a98a8806841973663ebd37f
- https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=05ef96a3aa9d6823ab431d458c88780fe8e2ef81

**Comment by ralphbean** [comment]
Looks good in staging:  https://pkgs.stg.fedoraproject.org/cgit/rpms-checks

**Comment by pypingou** [comment]
One issue with this approach is that you can't give some access to the check repo without giving them access to the main repo, which iirc is something QA was interested in.

**Comment by ralphbean** [comment]
That's correct.  We talked about it in irc yesterday with @tflink and he agreed that just copying the existing package ACLs would work for now, and if they have specific requests to make it more flexible in the future, we can go back and add a real namespace to pkgdb with some kind of syncing/updating.

**Comment by ralphbean** [comment]
OK - these are created in prod now:  http://pkgs.fedoraproject.org/cgit/rpms-checks
