### ISSUE TITLE
New package can be created without being reviewed

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#330]
I'm not sure where the bug is, but take a look at this ticket:

https://bugzilla.redhat.com/show_bug.cgi?id=1318359

The user filed the review request and then shortly afterwards also requested that the new package be created in pkgdb, before anyone reviewed the ticket.

Then, the pkgdb admin action was completed, also before any review had taken place.

Perhaps some script in that chain needs to check of the review has been approved before it will proceed?

**Comment by pypingou** [comment]
Admin actions are normally ran by a human, there is nothing automatic

/me goes investigate

**Comment by pypingou** [comment]
hm I think I know, it's a bug in pkgdb-cli and Jon isn't running the latest version that is in updates-testing

**Comment by pypingou** [comment]
I've just sent an email to Jon asking him to update to pkgdb-admin 2.11

**Comment by pypingou** [comment]
This should be fixed in 2.12 which contains this fix: https://github.com/fedora-infra/packagedb-cli/pull/80
