### ISSUE TITLE
why libcdaudio is in critpath and how I remove from there ?

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/pkgdb2#339]
https://admin.fedoraproject.org/pkgdb/api/critpath?tg_format=plain&collctn_list=f24
I have 4 times libcdaudio in list of above link . but don't find libcdaudio in comps [1]  or somewhere else.  
Is libcdaudio in critpath ? or is api/critpath that is not correct ? 

Thanks.

[1] https://fedoraproject.org/wiki/Critical_path_package

**Comment by sergiomb2** [comment]
https://fedorahosted.org/rel-eng/ticket/6396 , may help here.

**Comment by pypingou** [comment]
So looks like this issue is resolved?

If it isn't it's not really a bug in pkgdb2 more something out of sync from the source of info :)

So let's close this ticket, but thanks for finding out it is/was out-dated :)
