### ISSUE TITLE
Constrain some namespaces to only allow certain branches

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/pkgdb2#341]
This was first reported downstream in the modularity efforts here: http://taiga.fedorainfracloud.org/project/modularity/us/130?kanban-status=470

We can maybe do this with a simple config file entry that sets a 'branch policy' for certain namespaces.. something that just forbids creating branches on this or that namespace if the branchname matches a given regex?

**Comment by pypingou** [comment]
sounds doable and reasonable
