### ISSUE TITLE
Pagination of admin action list is missing URL parameters.

### ISSUE THREAD

**Issue by tyll** [fedora-infra/pkgdb2#346]
The link on

    https://admin.fedoraproject.org/pkgdb/admin/actions/?package=&packager=&action=&status=All

for the next page is:

    https://admin.fedoraproject.org/pkgdb/admin/actions/?from_date=&page=2&package=

It is missing the ```status=All``` URL-parameter to filter for all actions. Therefore it does not actually show page two of the query.

**Comment by pypingou** [comment]
Thanks for the report
