### ISSUE TITLE
Non-administrator gets treated slightly like an administrator

### ISSUE THREAD

**Issue by mulkieran** [fedora-infra/pkgdb2#351]
I'm not a package administrator.

I requested an EPEL 7 branch on python-pyudev.

Then when I log in I get a little message telling me to review the request:
![screenshot from 2016-05-09 08-48-37](https://cloud.githubusercontent.com/assets/1218366/15113530/da529e92-15c2-11e6-9404-6aa8de37f01d.png)

This is wrong, because I'm not an administrator and shouldn't be able to.

I click on the message and end up on a new screen:
![screenshot from 2016-05-09 08-45-18](https://cloud.githubusercontent.com/assets/1218366/15113452/62df4c84-15c2-11e6-9f74-29a4d522a4d3.png)
That tells me I'm a current administrator and can select Approved or Blocked.
This is wrong, because I'm not an administrator.

The menu only contains the options "Pending" and "Obsolete", which may or may not be correct, I'm not sure.

**Comment by pypingou** [comment]
> The menu only contains the options "Pending" and "Obsolete", which may or may not be correct, I'm not sure.

This is actually correct as the idea is to offer you the possibility to change your mind and obsolete your request.

**Comment by pypingou** [comment]
I am going to close this ticket. Feel free to re-open it if you think something could/should be changed.

Thanks for your report :)
