### ISSUE TITLE
fedmsg for pkgdb when a package is approved for unretirement

### ISSUE THREAD

**Issue by mohanboddu** [fedora-infra/pkgdb2#378]
We are writting a script which will unblock a package in Koji if it is approved for unretirement in pkgdb. It would be really helpful if a message is published when it does happens.

**Comment by pypingou** [comment]
I would actually expect https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.pkgdb.package.update.status to cover also unretire, odd that it doesn't :(

**Comment by keszybz** [comment]
That sounds like a good idea. Maybe it's a matter of just adding one right line somewhere in pkgdb?

**Comment by pypingou** [comment]
Fixed in the proposed PR :)
