### ISSUE TITLE
Request a new package: default namespace is not rpm

### ISSUE THREAD

**Issue by ingvagabund** [fedora-infra/pkgdb2#382]
Hi,

noticing the namespace in the request [1] defaults to ``docker`` now. Before, it defaulted to ``rpms``. As a pkgdb2 user used to ``rpms`` namespace being default, someone does not have to notice that and can create a request for docker namespace.

If it is an intention to make the ``docker`` namespace default, don't hesitate to close the issue. Otherwise, it makes more sense to change it to ``rpms``.

[1] https://admin.fedoraproject.org/pkgdb/request/package/

Regards
Jan

**Comment by pypingou** [comment]
Fixed in https://github.com/fedora-infra/pkgdb2/pull/377 :)

Thanks for the report though :)
