### ISSUE TITLE
Removing myself from all ACLs in a package did not remove me from the package-owner@ mailing list

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/pkgdb2#406]
I recently removed myself from all ACLs on Pulp:

https://admin.fedoraproject.org/pkgdb/package/rpms/pulp/

However, I still receive e-mails sent to pulp-owner@fedoraproject.org. I would expect to stop receiving mails sent to that address.

**Comment by pypingou** [comment]
Looks like this is performed hourly by a cron job on bastion and looking at the file, it seems that you are no longer on the list.

So unless we want to make this a fedmsg-trigger task (which we could but should likely discuss it first on the list or in another ticket), I think this ticket can be closed :)

Sorry for the inconvenience.

**Comment by bowlofeggs** [comment]
Hello @pypingou!

I think it was not a bug after all! I just realized that the e-mail is also to python-celery-owner, and I am on *that* list. It's funny that I just removed myself from Pulp e-mails, and I hadn't realized the e-mail (about broken dependencies due to a celery upgrade) was coming to me that way. Sorry for the noise!

**Comment by pypingou** [comment]
Cool it got sorted out :)

Thanks for the follow-up!
