### ISSUE TITLE
Approve commit access once per user

### ISSUE THREAD

**Issue by voxik** [fedora-infra/pkgdb2#84]
When somebody asks me for permissions of all Fedora/EPEL branches, I have to go through every branch column in Edit Commit Access page [1] and set it explicitly on approved. Is there chance to approve them in once?

It might be some additional column? May be it could be just some client side JS, which would update combo states in every branch column? When I have no right to approve right for some branch, the setting will fail just for that specific branch (actually this works already, so it should not be any issue).

[1] https://admin.fedoraproject.org/pkgdb/package/rubygem-rack/acl/commit/

**Comment by juhp** [comment]
I would prefer if this could be implemented as a bit of UI: something like an [Approve requested] button.
One doesn't always want to approve all branches (even unrequested ones;) in one go. :)

cf https://fedorahosted.org/pkgdb2/ticket/46

**Comment by pypingou** [comment]
The current behavior is more than [Approve All] it can also be [Deny All], you could use it to make everything Denied but the one you're interested in granted or vice-versa
